name: Metrics Right
on:
  schedule: [{cron: "0 4 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: General Right
        uses: lowlighter/metrics@latest
        with:
          filename: general_R.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_gist: ${{ secrets.GIST }}
          output_action: gist
          user: thegdsks
          base: ""
          config_timezone: America/Chicago
          repositories_forks: yes
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_followup_indepth: yes
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers
